In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return (1/(1+np.exp(-x)))
    

In [3]:
input = np.array([
    [1,0,1],
    [1,1,1],
    [0,1,1],
    [0,0,1],
])

In [4]:
t_output = np.array([[1,1,0,0]]).T
t_output

array([[1],
       [1],
       [0],
       [0]])

In [5]:
t_out = np.array([
       [1],
       [1],
       [0],
       [0]
                 ])
t_out

array([[1],
       [1],
       [0],
       [0]])

In [6]:
weights = 2*np.random.random((3,1)) -1
weights

array([[-0.41079594],
       [-0.98933589],
       [ 0.131338  ]])

In [7]:
def s_der(x):
    return (x*(1-x))

In [8]:
# for iter in range(1):
for i in range(10000):
    output = sigmoid(np.dot(input, weights))
    error = t_output-output
    upd = error*s_der(output)
    weights+= np.dot(input.T, upd)

In [9]:
output

array([[0.9935922 ],
       [0.99211497],
       [0.00786277],
       [0.00967216]])

In [10]:
np.round(output)

array([[1.],
       [1.],
       [0.],
       [0.]])

In [11]:
 sigmoid(63245672121476)

1.0

In [ ]:
output = sigmoid(input)
out_
error = out-output_t